--- 
- name: Create Users
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  
    - name: Create a user 'johnd' with a home directory
      ansible.builtin.user:
        name: johnd
        create_home: yes

    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: johnd
        comment: John Doe
        uid: 1040
        group: admin

    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest
      tags: http
      register: command_output

    - name: Shows the exit code
      ansible.builtin.debug:
        msg: "{{ command_output.rc }}"

    - name: Install chrony
      ansible.builtin.yum:
        name: chrony
        state: present

    - name: Enable and start chronyd
      ansible.builtin.service:
        name: chronyd
        enabled: true
        state: started

